---
# defaults file for ec2_ami_upgrade
security_group_name: "PS-Rhel8-Gold-AMI-SG"
vpc_id: "vpc-075a92881928d8deb" #CDMPreStagingVPC
cidr_ip: "52.61.62.104/32"
rule_desc: "allow ssh"
ec2_name: "PS-Rhel8-Gold-AMI-EC2"
key_name: "ECE-Installer-20200811_010627"
aws_region: "us-gov-west-1"
instance_type: "t2.large"
image_id: "ami-0599ce1f64765f794" #RHEL8-LVM-STIG-06282023-NB-AMI-128GB-09122023
vpc_subnet_id: "subnet-0459d556d70c10e3d" #CDMPreStagingVPC-public-us-gov-west-1a
count: "1"
ami_name: "PS-Rhel8-Gold-AMI-128GB-Latest"


